alias ll='ls -Gahl'
alias ls='ls -G'
alias be='bundle exec'
alias gpl='git pull'
alias gps='git push'
alias gm='git commit -v'
alias gma='git commit --amend --no-edit'
alias grm='git rebase master --preserve-merges'
alias grc='git rebase --continue'
alias gl='git log'
alias gs='git status'
alias gc='git checkout'
alias gd='git diff --color'
alias gdc='git diff --cached --color'
alias ga='git add'
alias gb='git branch'
alias gbn='git checkout -b'
alias gx='git branch --merged | grep -v "master" | grep -v "release" | xargs -n 1 git branch -d'

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -G --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
